### ISSUE TITLE
Gist support

### ISSUE THREAD

**Issue by sepehr** [bntzio/github-classic#1]
The extension does not work on the gist site:  

![gist](https://user-images.githubusercontent.com/23576/29611858-6db9b70a-8814-11e7-8b02-07a7a5df8079.png)

**Comment by bntzio** [comment]
@sepehr oh yeah! forgot the gist, i'm going to fix that in just a moment 🙂 thanks! 👍

**Comment by bntzio** [comment]
@sepehr done! 😄 please [update](https://chrome.google.com/webstore/detail/github-classic/cjoajojnjmnefgkhnnpfjhmllgeeadjk) the extension! 🔌 [v1.1.0](https://github.com/bntzio/github-classic/releases/tag/v1.1.0)

**Comment by sepehr** [comment]
Perfect, thanks!
